iaas_settings:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  compilation_cloud_properties: {}
  resource_pool_cloud_properties:
    - name: access_z1
      cloud_properties: {}
    - name: access_z2
      cloud_properties: {}
    - name: access_z3
      cloud_properties: {}
    - name: brain_z1
      cloud_properties: {}
    - name: brain_z2
      cloud_properties: {}
    - name: brain_z3
      cloud_properties: {}
    - name: cc_bridge_z1
      cloud_properties: {}
    - name: cc_bridge_z2
      cloud_properties: {}
    - name: cc_bridge_z3
      cloud_properties: {}
    - name: cell_z1
      cloud_properties: {}
    - name: cell_z2
      cloud_properties: {}
    - name: cell_z3
      cloud_properties: {}
    - name: colocated_z1
      cloud_properties: {}
    - name: colocated_z2
      cloud_properties: {}
    - name: colocated_z3
      cloud_properties: {}
    - name: database_z1
      cloud_properties: {}
    - name: database_z2
      cloud_properties: {}
    - name: database_z3
      cloud_properties: {}
    - name: route_emitter_z1
      cloud_properties: {}
    - name: route_emitter_z2
      cloud_properties: {}
    - name: route_emitter_z3
      cloud_properties: {}
  subnet_configs:
  - name: diego1
    type: manual
    subnets:
    - range: 10.244.16.0/24
      gateway: 10.244.16.1
      reserved:
      - 10.244.16.1
      static:
      - "10.244.16.2-10.244.16.50"
      cloud_properties: {}
  - name: diego2
    type: manual
    subnets:
    - range: 10.244.18.0/24
      gateway: 10.244.18.1
      reserved:
      - 10.244.18.1
      static:
      - "10.244.18.2-10.244.18.50"
      cloud_properties: {}
  - name: diego3
    type: manual
    subnets:
    - range: 10.244.20.0/24
      gateway: 10.244.20.1
      reserved:
      - 10.244.20.1
      static:
      - "10.244.20.2-10.244.20.50"
      cloud_properties: {}
