groups:
- name: postgres
  jobs:
  - deploy-with-cf
  - deploy-with-diego
  - test-with-diego
  - delete-deployments
  - create-final-release
  - merge-master-into-develop

resources:
- name: cf-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-release.git
    branch: develop

- name: postgres-release-develop
  type: git
  source:
    uri: https://github.com/cloudfoundry/postgres-release.git
    branch: develop

- name: postgres-ci-env
  type: git
  source:
    uri: git@github.com:cloudfoundry/postgres-ci-env
    branch: master
    private_key: {{postgres_ci_env_private_key}}

- name: diego-release-master
  type: git
  source:
    branch: master
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry/diego-release.git

- name: oss-s3-buckets-stack
  type: git
  source:
    branch: master
    private_key: {{oss-s3-buckets-stack-private-key}}
    uri: git@github.com:cloudfoundry/oss-s3-buckets-stack.git

- name: postgres-release-master
  type: git
  source:
    uri: git@github.com:cloudfoundry/postgres-release.git
    branch: master
    private_key: {{postgres-release-private-key}}

- name: postgres-release-merge-target
  type: git
  source:
    uri: git@github.com:cloudfoundry/postgres-release.git
    branch: develop
    private_key: {{postgres-release-private-key}}

jobs:
- name: deploy-with-cf
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: cf-release
    - get: postgres-ci-env
    - get: postgres-release
      resource: postgres-release-develop
  - task: deploy-with-cf
    file: postgres-release/ci/scripts/deploy-with-cf/task.yml
    params:
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
      HAPROXY_DEPLOYMENT: pgci-ha
      CF_DEPLOYMENT: {{cf_deployment}}
      API_USER: {{api_user}}
      API_PASSWORD: {{api_password}}

- name: deploy-with-diego
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: postgres-ci-env
    - get: diego-release
      resource: diego-release-master
    - get: postgres-release
      resource: postgres-release-develop
      passed: [deploy-with-cf]
      trigger: true
  - task: deploy-with-diego
    file: postgres-release/ci/scripts/deploy-with-diego/task.yml
    params:
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
      CF_DEPLOYMENT: {{cf_deployment}}
      API_USER: {{api_user}}
      API_PASSWORD: {{api_password}}

- name: test-with-diego
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: postgres-release
      resource: postgres-release-develop
      passed: [deploy-with-diego]
      trigger: true
  - task: test-with-diego
    file: postgres-release/ci/scripts/test-with-diego/task.yml
    params:
        BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
        BOSH_USER: {{postgres_cf_bosh_user}}
        BOSH_PASSWORD: {{postgres_cf_bosh_password}}
        DEPLOYMENT_NAME: {{cf_deployment}}

- name: delete-deployments
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: postgres-release
      resource: postgres-release-develop
      passed: [test-with-diego]
      trigger: true
  - task: delete-diego-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params:
      DEPLOYMENT_NAME: pgci-cf-diego
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
  - task: delete-cf-deployment
    file: postgres-release/ci/scripts/run-bosh-delete/task.yml
    params:
      DEPLOYMENT_NAME: {{cf_deployment}}
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}
  - task: cleanup-releases
    file: postgres-release/ci/scripts/run-bosh-cleanup/task.yml
    params:
      BOSH_DIRECTOR: {{postgres_cf_bosh_director}}
      BOSH_USER: {{postgres_cf_bosh_user}}
      BOSH_PASSWORD: {{postgres_cf_bosh_password}}

- name: create-final-release
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: postgres-release
      resource: postgres-release-develop
    - get: oss-s3-buckets-stack
      resource: oss-s3-buckets-stack
    - get: release-repo
      resource: postgres-release-develop
      passed: [delete-deployments]
      trigger: true
    - get: release-repo-master
      resource: postgres-release-master
  - task: create-final-release
    file: postgres-release/ci/scripts/create-final-release/task.yml
    params:
      RELEASE_NAME: postgres
  - put: postgres-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v

- name: merge-master-into-develop
  serial_groups: [cf]
  plan:
  - aggregate:
    - get: postgres-release
      resource: postgres-release-develop
    - get: release-repo-master
      resource: postgres-release-master
      trigger: true
    - get: release-repo
      resource: postgres-release-merge-target
  - task: merge-master-into-develop
    file: postgres-release/ci/scripts/merge-master-into-develop/task.yml
  - put: postgres-release-merge-target
    params:
      repository: final-release-repo
