iaas_settings:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  compilation_cloud_properties: {}
  resource_pool_cloud_properties:
    - name: access_z1
      cloud_properties: {}
    - name: access_z2
      cloud_properties: {}
    - name: access_z3
      cloud_properties: {}
    - name: brain_z1
      cloud_properties: {}
    - name: brain_z2
      cloud_properties: {}
    - name: brain_z3
      cloud_properties: {}
    - name: cc_bridge_z1
      cloud_properties: {}
    - name: cc_bridge_z2
      cloud_properties: {}
    - name: cc_bridge_z3
      cloud_properties: {}
    - name: cell_z1
      cloud_properties: {}
    - name: cell_z2
      cloud_properties: {}
    - name: cell_z3
      cloud_properties: {}
    - name: colocated_z1
      cloud_properties: {}
    - name: colocated_z2
      cloud_properties: {}
    - name: colocated_z3
      cloud_properties: {}
    - name: database_z1
      cloud_properties: {}
    - name: database_z2
      cloud_properties: {}
    - name: database_z3
      cloud_properties: {}
    - name: route_emitter_z1
      cloud_properties: {}
    - name: route_emitter_z2
      cloud_properties: {}
    - name: route_emitter_z3
      cloud_properties: {}
  subnet_configs:
  - name: diego1
    type: manual
    subnets:
    - range: 10.244.34.0/30
      reserved:
      - 10.244.34.1
      static:
      - 10.244.34.2
      cloud_properties: {}
    - range: 10.244.34.4/30
      reserved:
      - 10.244.34.5
      static:
      - 10.244.34.6
      cloud_properties: {}
    - range: 10.244.34.8/30
      reserved:
      - 10.244.34.9
      static:
      - 10.244.34.10
      cloud_properties: {}
    - range: 10.244.34.12/30
      reserved:
      - 10.244.34.13
      static:
      - 10.244.34.14
      cloud_properties: {}
    - range: 10.244.34.16/30
      reserved:
      - 10.244.34.17
      static:
      - 10.244.34.18
      cloud_properties: {}
    - range: 10.244.34.20/30
      reserved:
      - 10.244.34.21
      static:
      - 10.244.34.22
      cloud_properties: {}
    - range: 10.244.34.24/30
      reserved:
      - 10.244.34.25
      static:
      - 10.244.34.26
      cloud_properties: {}
    - range: 10.244.34.28/30
      reserved:
      - 10.244.34.29
      static:
      - 10.244.34.30
      cloud_properties: {}
    - range: 10.244.34.32/30
      reserved:
      - 10.244.34.33
      static:
      - 10.244.34.34
      cloud_properties: {}
    - range: 10.244.34.36/30
      reserved:
      - 10.244.34.37
      static:
      - 10.244.34.38
      cloud_properties: {}
    - range: 10.244.34.40/30
      reserved:
      - 10.244.34.41
      static:
      - 10.244.34.42
      cloud_properties: {}
    - range: 10.244.34.44/30
      reserved:
      - 10.244.34.45
      static:
      - 10.244.34.46
      cloud_properties: {}
    - range: 10.244.34.48/30
      reserved:
      - 10.244.34.49
      static:
      - 10.244.34.50
      cloud_properties: {}
    - range: 10.244.34.52/30
      reserved:
      - 10.244.34.53
      static:
      - 10.244.34.54
      cloud_properties: {}
    - range: 10.244.34.56/30
      reserved:
      - 10.244.34.57
      static:
      - 10.244.34.58
      cloud_properties: {}
    - range: 10.244.34.60/30
      reserved:
      - 10.244.34.61
      static:
      - 10.244.34.62
      cloud_properties: {}
    - range: 10.244.34.64/30
      reserved:
      - 10.244.34.65
      static:
      - 10.244.34.66
      cloud_properties: {}
    - range: 10.244.34.68/30
      reserved:
      - 10.244.34.69
      static:
      - 10.244.34.70
      cloud_properties: {}
    - range: 10.244.34.72/30
      reserved:
      - 10.244.34.73
      static:
      - 10.244.34.74
      cloud_properties: {}
    - range: 10.244.34.76/30
      reserved:
      - 10.244.34.77
      static:
      - 10.244.34.78
      cloud_properties: {}
    - range: 10.244.34.80/30
      reserved:
      - 10.244.34.81
      static:
      - 10.244.34.82
      cloud_properties: {}
    - range: 10.244.34.84/30
      reserved:
      - 10.244.34.85
      static: []
      cloud_properties: {}
    - range: 10.244.34.88/30
      reserved:
      - 10.244.34.89
      static: []
      cloud_properties: {}
    - range: 10.244.34.92/30
      reserved:
      - 10.244.34.93
      static: []
      cloud_properties: {}
    - range: 10.244.34.96/30
      reserved:
      - 10.244.34.97
      static: []
      cloud_properties: {}
    - range: 10.244.34.100/30
      reserved:
      - 10.244.34.101
      static: []
      cloud_properties: {}
    - range: 10.244.34.104/30
      reserved:
      - 10.244.34.105
      static: []
      cloud_properties: {}
    - range: 10.244.34.108/30
      reserved:
      - 10.244.34.109
      static: []
      cloud_properties: {}
    - range: 10.244.34.112/30
      reserved:
      - 10.244.34.113
      static: []
      cloud_properties: {}
    - range: 10.244.34.116/30
      reserved:
      - 10.244.34.117
      static: []
      cloud_properties: {}
    - range: 10.244.34.120/30
      reserved:
      - 10.244.34.121
      static: []
      cloud_properties: {}
  - name: diego2
    type: manual
    subnets:
    - range: 10.244.36.0/30
      reserved:
      - 10.244.36.1
      static:
      - 10.244.36.2
      cloud_properties: {}
    - range: 10.244.36.4/30
      reserved:
      - 10.244.36.5
      static:
      - 10.244.36.6
      cloud_properties: {}
    - range: 10.244.36.8/30
      reserved:
      - 10.244.36.9
      static:
      - 10.244.36.10
      cloud_properties: {}
    - range: 10.244.36.12/30
      reserved:
      - 10.244.36.13
      static:
      - 10.244.36.14
      cloud_properties: {}
    - range: 10.244.36.16/30
      reserved:
      - 10.244.36.17
      static:
      - 10.244.36.18
      cloud_properties: {}
    - range: 10.244.36.20/30
      reserved:
      - 10.244.36.21
      static:
      - 10.244.36.22
      cloud_properties: {}
    - range: 10.244.36.24/30
      reserved:
      - 10.244.36.25
      static:
      - 10.244.36.26
      cloud_properties: {}
    - range: 10.244.36.28/30
      reserved:
      - 10.244.36.29
      static:
      - 10.244.36.30
      cloud_properties: {}
    - range: 10.244.36.32/30
      reserved:
      - 10.244.36.33
      static:
      - 10.244.36.34
      cloud_properties: {}
    - range: 10.244.36.36/30
      reserved:
      - 10.244.36.37
      static:
      - 10.244.36.38
      cloud_properties: {}
    - range: 10.244.36.40/30
      reserved:
      - 10.244.36.41
      static:
      - 10.244.36.42
      cloud_properties: {}
    - range: 10.244.36.44/30
      reserved:
      - 10.244.36.45
      static:
      - 10.244.36.46
      cloud_properties: {}
    - range: 10.244.36.48/30
      reserved:
      - 10.244.36.49
      static:
      - 10.244.36.50
      cloud_properties: {}
    - range: 10.244.36.52/30
      reserved:
      - 10.244.36.53
      static:
      - 10.244.36.54
      cloud_properties: {}
    - range: 10.244.36.56/30
      reserved:
      - 10.244.36.57
      static:
      - 10.244.36.58
      cloud_properties: {}
    - range: 10.244.36.60/30
      reserved:
      - 10.244.36.61
      static:
      - 10.244.36.62
      cloud_properties: {}
    - range: 10.244.36.64/30
      reserved:
      - 10.244.36.65
      static:
      - 10.244.36.66
      cloud_properties: {}
    - range: 10.244.36.68/30
      reserved:
      - 10.244.36.69
      static:
      - 10.244.36.70
      cloud_properties: {}
    - range: 10.244.36.72/30
      reserved:
      - 10.244.36.73
      static:
      - 10.244.36.74
      cloud_properties: {}
    - range: 10.244.36.76/30
      reserved:
      - 10.244.36.77
      static:
      - 10.244.36.78
      cloud_properties: {}
    - range: 10.244.36.80/30
      reserved:
      - 10.244.36.81
      static:
      - 10.244.36.82
      cloud_properties: {}
    - range: 10.244.36.84/30
      reserved:
      - 10.244.36.85
      static: []
      cloud_properties: {}
    - range: 10.244.36.88/30
      reserved:
      - 10.244.36.89
      static: []
      cloud_properties: {}
    - range: 10.244.36.92/30
      reserved:
      - 10.244.36.93
      static: []
      cloud_properties: {}
    - range: 10.244.36.96/30
      reserved:
      - 10.244.36.97
      static: []
      cloud_properties: {}
    - range: 10.244.36.100/30
      reserved:
      - 10.244.36.101
      static: []
      cloud_properties: {}
    - range: 10.244.36.104/30
      reserved:
      - 10.244.36.105
      static: []
      cloud_properties: {}
    - range: 10.244.36.108/30
      reserved:
      - 10.244.36.109
      static: []
      cloud_properties: {}
    - range: 10.244.36.112/30
      reserved:
      - 10.244.36.113
      static: []
      cloud_properties: {}
    - range: 10.244.36.116/30
      reserved:
      - 10.244.36.117
      static: []
      cloud_properties: {}
    - range: 10.244.36.120/30
      reserved:
      - 10.244.36.121
      static: []
      cloud_properties: {}
  - name: diego3
    type: manual
    subnets:
    - range: 10.244.38.0/30
      reserved:
      - 10.244.38.1
      static:
      - 10.244.38.2
      cloud_properties: {}
    - range: 10.244.38.4/30
      reserved:
      - 10.244.38.5
      static:
      - 10.244.38.6
      cloud_properties: {}
    - range: 10.244.38.8/30
      reserved:
      - 10.244.38.9
      static:
      - 10.244.38.10
      cloud_properties: {}
    - range: 10.244.38.12/30
      reserved:
      - 10.244.38.13
      static:
      - 10.244.38.14
      cloud_properties: {}
    - range: 10.244.38.16/30
      reserved:
      - 10.244.38.17
      static:
      - 10.244.38.18
      cloud_properties: {}
    - range: 10.244.38.20/30
      reserved:
      - 10.244.38.21
      static:
      - 10.244.38.22
      cloud_properties: {}
    - range: 10.244.38.24/30
      reserved:
      - 10.244.38.25
      static:
      - 10.244.38.26
      cloud_properties: {}
    - range: 10.244.38.28/30
      reserved:
      - 10.244.38.29
      static:
      - 10.244.38.30
      cloud_properties: {}
    - range: 10.244.38.32/30
      reserved:
      - 10.244.38.33
      static:
      - 10.244.38.34
      cloud_properties: {}
    - range: 10.244.38.36/30
      reserved:
      - 10.244.38.37
      static:
      - 10.244.38.38
      cloud_properties: {}
    - range: 10.244.38.40/30
      reserved:
      - 10.244.38.41
      static:
      - 10.244.38.42
      cloud_properties: {}
    - range: 10.244.38.44/30
      reserved:
      - 10.244.38.45
      static:
      - 10.244.38.46
      cloud_properties: {}
    - range: 10.244.38.48/30
      reserved:
      - 10.244.38.49
      static:
      - 10.244.38.50
      cloud_properties: {}
    - range: 10.244.38.52/30
      reserved:
      - 10.244.38.53
      static:
      - 10.244.38.54
      cloud_properties: {}
    - range: 10.244.38.56/30
      reserved:
      - 10.244.38.57
      static:
      - 10.244.38.58
      cloud_properties: {}
    - range: 10.244.38.60/30
      reserved:
      - 10.244.38.61
      static:
      - 10.244.38.62
      cloud_properties: {}
    - range: 10.244.38.64/30
      reserved:
      - 10.244.38.65
      static:
      - 10.244.38.66
      cloud_properties: {}
    - range: 10.244.38.68/30
      reserved:
      - 10.244.38.69
      static:
      - 10.244.38.70
      cloud_properties: {}
    - range: 10.244.38.72/30
      reserved:
      - 10.244.38.73
      static:
      - 10.244.38.74
      cloud_properties: {}
    - range: 10.244.38.76/30
      reserved:
      - 10.244.38.77
      static:
      - 10.244.38.78
      cloud_properties: {}
    - range: 10.244.38.80/30
      reserved:
      - 10.244.38.81
      static:
      - 10.244.38.82
      cloud_properties: {}
    - range: 10.244.38.84/30
      reserved:
      - 10.244.38.85
      static: []
      cloud_properties: {}
    - range: 10.244.38.88/30
      reserved:
      - 10.244.38.89
      static: []
      cloud_properties: {}
    - range: 10.244.38.92/30
      reserved:
      - 10.244.38.93
      static: []
      cloud_properties: {}
    - range: 10.244.38.96/30
      reserved:
      - 10.244.38.97
      static: []
      cloud_properties: {}
    - range: 10.244.38.100/30
      reserved:
      - 10.244.38.101
      static: []
      cloud_properties: {}
    - range: 10.244.38.104/30
      reserved:
      - 10.244.38.105
      static: []
      cloud_properties: {}
    - range: 10.244.38.108/30
      reserved:
      - 10.244.38.109
      static: []
      cloud_properties: {}
    - range: 10.244.38.112/30
      reserved:
      - 10.244.38.113
      static: []
      cloud_properties: {}
    - range: 10.244.38.116/30
      reserved:
      - 10.244.38.117
      static: []
      cloud_properties: {}
    - range: 10.244.38.120/30
      reserved:
      - 10.244.38.121
      static: []
      cloud_properties: {}
