iaas_settings:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  compilation_cloud_properties: {}
  resource_pool_cloud_properties:
    - name: access_z1
      cloud_properties: {}
    - name: access_z2
      cloud_properties: {}
    - name: access_z3
      cloud_properties: {}
    - name: brain_z1
      cloud_properties: {}
    - name: brain_z2
      cloud_properties: {}
    - name: brain_z3
      cloud_properties: {}
    - name: cc_bridge_z1
      cloud_properties: {}
    - name: cc_bridge_z2
      cloud_properties: {}
    - name: cc_bridge_z3
      cloud_properties: {}
    - name: cell_z1
      cloud_properties: {}
    - name: cell_z2
      cloud_properties: {}
    - name: cell_z3
      cloud_properties: {}
    - name: colocated_z1
      cloud_properties: {}
    - name: colocated_z2
      cloud_properties: {}
    - name: colocated_z3
      cloud_properties: {}
    - name: database_z1
      cloud_properties: {}
    - name: database_z2
      cloud_properties: {}
    - name: database_z3
      cloud_properties: {}
    - name: route_emitter_z1
      cloud_properties: {}
    - name: route_emitter_z2
      cloud_properties: {}
    - name: route_emitter_z3
      cloud_properties: {}
  subnet_configs:
  - name: diego1
    type: manual
    subnets:
    - range: 10.244.22.0/24
      gateway: 10.244.22.1
      reserved:
      - 10.244.22.1
      static:
      - "10.244.22.2-10.244.22.50"
      cloud_properties: {}
  - name: diego2
    type: manual
    subnets:
    - range: 10.244.24.0/24
      gateway: 10.244.24.1
      reserved:
      - 10.244.24.1
      static:
      - "10.244.24.2-10.244.24.50"
      cloud_properties: {}
  - name: diego3
    type: manual
    subnets:
    - range: 10.244.26.0/24
      gateway: 10.244.26.1
      reserved:
      - 10.244.26.1
      static:
      - "10.244.26.2-10.244.26.50"
      cloud_properties: {}
