---
dev_name: paasta-container-full
latest_release_filename: "/home/ihocho/workspace/paasta-2.0/paasta-2.0-full-sources/paasta-container-2.0/dev_releases/paasta-container-full/paasta-container-full-0+dev.1.yml"
